In [1]:
import pandas as pd

df = pd.read_csv('StudentsPerformance.csv')
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
df['math score'] = df.fillna(df['math score'].mean())
df['reading score'] = df.fillna(df['reading score'].mean())
df['writing score'] = df.fillna(df['writing score'].mean())

In [3]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [4]:
print("Average Marks")
print("math score average: ", df['math score'].mean())
print("reading score average: ", df['reading score'].mean())
print("writing score average: ", df['writing score'].mean())

Average Marks
math score average:  66.089
reading score average:  69.169
writing score average:  68.054

In [5]:
print("Minimmum Marks")
print("math score minimum: ", df['math score'].min())
print("reading score minimum: ", df['reading score'].min())
print("writing score minimum: ", df['writing score'].min())

Minimmum Marks
math score minimum:  0
reading score minimum:  17
writing score minimum:  10

In [6]:
print("Maximum Marks")
print("math score maximum: ", df['math score'].max())
print("reading score maximum: ", df['reading score'].max())
print("writing score maximum: ", df['writing score'].max())

Maximum Marks
math score maximum:  100
reading score maximum:  100
writing score maximum:  100

In [7]:
print("Median")
print("math score median: ", df['math score'].median())
print("reading score median: ", df['reading score'].median())
print("writing score median: ", df['writing score'].median())

Median
math score median:  66.0
reading score median:  70.0
writing score median:  69.0

In [ ]:
print("Mode")
print("math score mode: ", df['math score'].mode())
print("reading score mode: ", df['reading score'].mode())
print("writing score mode: ", df['writing score'].mode())

Mode
math score mode:  0    65
Name: math score, dtype: int64
reading score mode:  0    72
Name: reading score, dtype: int64
writing score mode:  0    74
Name: writing score, dtype: int64

In [10]:
print("Sorting...")
print("Sorted by parental level of education")
df.sort_values(by='parental level of education', ascending=True).head()

Sorting...
Sorted by parental level of education

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
5,female,group B,associate's degree,standard,none,71,83,78
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
19,female,group C,associate's degree,free/reduced,none,54,58,61